### ISSUE TITLE
add keywords like biowin to description

### ISSUE THREAD

**Issue by HoWilgh** [vermi0ffh/ha-windhager#5]
I noticed that it is not possible to find this project by searching for eg. "BioWin2" or "BioWin Windhager" in GitHub.
It would be good to add some explanation or at least keywords like "BioWin, Windhager, heating, home-assistant, sensors, data" to the existing "Windhager integration in home assistant".

How about "Integration of heatings/boilers of Windhager into home assistant home-automation system. Tested with BioWin 2 Touch.

**Comment by vermi0ffh** [comment]
Good idea, I added it to the readme !
